[package]
name = "tdctl"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
clap = { version = "4.5.58", features = ["derive"] }
libc = "0.2.182"
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }

[dev-dependencies]
libc = "0.2.182"
tempfile = "3.25.0"
